import json

f = open("mapa-virtual.json", encoding='utf-8')
bd = json.load(f)
f.close()

cidades = bd["cidades"]

ligacoes = bd["ligacoes"]

print("""@prefix : <http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual/> .

<http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#destino
:destino rdf:type owl:ObjectProperty ;
         rdfs:domain :Ligação ;
         rdfs:range :Cidade .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#origem
:origem rdf:type owl:ObjectProperty ;
        rdfs:domain :Ligação ;
        rdfs:range :Cidade .


#################################################################
#    Data properties
#################################################################

###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#descrição
:descrição rdf:type owl:DatatypeProperty ;
           rdfs:domain :Cidade ;
           rdfs:range xsd:int .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#distrito
:distrito rdf:type owl:DatatypeProperty ;
          rdfs:domain :Cidade ;
          rdfs:range xsd:string .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#distância
:distância rdf:type owl:DatatypeProperty ;
           rdfs:domain :Ligação ;
           rdfs:range xsd:float .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#id
:id rdf:type owl:DatatypeProperty ;
    rdfs:domain :Cidade ;
    rdfs:range xsd:string .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#id_lig
:id_lig rdf:type owl:DatatypeProperty ;
        rdfs:domain :Ligação ;
        rdfs:range xsd:string .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#nome
:nome rdf:type owl:DatatypeProperty ;
      rdfs:domain :Cidade ;
      rdfs:range xsd:string .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#população
:população rdf:type owl:DatatypeProperty ;
           rdfs:domain :Cidade ;
           rdfs:range xsd:int .


#################################################################
#    Classes
#################################################################

###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#Cidade
:Cidade rdf:type owl:Class .


###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#Ligação
:Ligação rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################""")

for cidade in cidades:
    registo = f"""

###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#{cidade['id']}
:{cidade['id']} rdf:type owl:NamedIndividual ,
             :Cidade ;
    :descrição "{cidade['descrição']}" ;
    :distrito "{cidade['distrito']}" ;
    :id "{cidade['id']}" ;
    :nome "{cidade['nome']}" ;
    :população "{cidade['população']}"^^xsd:int .

""" 
    print(registo)

for ligacao in ligacoes:
    registo = f"""

###  http://www.semanticweb.org/vasco/ontologies/2024/2/mapa-virtual#{ligacao['id']}
:{ligacao['id']} rdf:type owl:NamedIndividual ,
              :Ligação ;
     :destino :{ligacao['destino']} ;
     :origem :{ligacao['origem']} ;
     :distância "{ligacao['distância']}"^^xsd:float ;
     :id "{ligacao['id']}" .    
"""
    
    print(registo)



print("""###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi""")